# Generated by Django 4.1.7 on 2024-03-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Form', '0003_user_confirm_password_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
