# Generated by Django 4.1.7 on 2024-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Form', '0004_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.TimeField(null=True),
        ),
    ]
